//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orlova_106.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int ID_sotrudnika { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Parol { get; set; }
    }
}
