//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orlova_106.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int ID_tovara { get; set; }
        public string Tip_tovara { get; set; }
        public Nullable<System.DateTime> Data_sdachi { get; set; }
        public Nullable<int> ID_klienta { get; set; }
        public Nullable<int> ID_sotrudnika { get; set; }
        public string Stomost { get; set; }
    
        public virtual Klient Klient { get; set; }
    }
}
